Add flow
PrefectHQ/prefect-hex pull request #15
Opened 2022-11-15 23:36 UTC by ahuang11

## Summary

## Relevant Issue(s)

## Checklist
- [ ] Summarized PR's changes in [CHANGELOG.md](https://github.com/PrefectHQ/prefect-hex/blob/main/CHANGELOG.md)

2022-11-16 00:11 UTC, zzstoatzz commented on README.md
> +    project_id = "012345c6-b67c-1234-1b2c-66e4ad07b9f3"
would this make sense as an arg of the user's flow?

2022-11-16 00:11 UTC, zzstoatzz commented on prefect_hex/project.py
> +        Trigger a Hex project run and wait for completion as a stand alone flow.
```suggestion
        Trigger a Hex project run and wait for completion as a stand-alone (or standalone) flow.
```

2022-11-16 00:11 UTC, zzstoatzz commented on prefect_hex/project.py
> +        ...
is this just a placeholder?

2022-11-16 00:12 UTC, ahuang11 commented on prefect_hex/project.py
> +        ...
Yup :D good catch

2022-11-16 00:12 UTC, zzstoatzz commented
also looks like we might need branch protection rules here

2022-11-16 00:28 UTC, zzstoatzz submitted a review, later dismissed
lgtm!

2022-11-28 19:24 UTC, desertaxle requested changes

2022-11-28 19:24 UTC, desertaxle commented on CHANGELOG.md
> +- Added `trigger_project_run_and_wait_for_completion_flow` flow - [#15](https://github.com/PrefectHQ/prefect-hex/pull/15)
```suggestion
- Added `trigger_project_run_and_wait_for_completion` flow - [#15](https://github.com/PrefectHQ/prefect-hex/pull/15)
```

2022-11-28 19:25 UTC, desertaxle approved these changes

2022-11-28 19:27 UTC, merged