Add tasks
PrefectHQ/prefect-hex pull request #2
Opened 2022-09-22 21:19 UTC by ahuang11

## Summary

## Relevant Issue(s)

## Checklist
- [ ] Summarized PR's changes in [CHANGELOG.md](https://github.com/PrefectHQ/prefect-hex/blob/main/CHANGELOG.md)

2022-09-22 21:54 UTC, desertaxle requested changes

2022-09-22 21:54 UTC, desertaxle commented on prefect_hex/credentials.py
> +    domain: str
Can we default this to `app.hex.tech`? Also add field descriptions?

2022-09-22 23:44 UTC, ahuang11 commented
![image](https://user-images.githubusercontent.com/15331990/191869864-cdae7b0e-fe37-41cf-8fa8-b815f0aacfcf.png)
![image](https://user-images.githubusercontent.com/15331990/191869878-f457f53c-e581-41c0-a67d-d16d0a260312.png)

2022-09-26 00:07 UTC, desertaxle approved these changes

2022-09-26 00:07 UTC, merged